name: Update Requirements

on:
  push:
    branches:
      - main  # This workflow triggers on pushes to the main branch

jobs:
  update-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Check directory contents
        run: |
          echo "Current directory contents:"
          ls -la
        working-directory: server  # List contents of the server directory

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: server

      - name: Update requirements.txt
        run: |
          pip freeze > requirements.txt
        working-directory: server

      - name: Check updated requirements.txt
        run: |
          echo "Updated requirements.txt contents:"
          cat requirements.txt
        working-directory: server

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add server/requirements.txt  # Path includes server directory
          git commit -m "Update requirements.txt" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
