name: Update Requirements

on:
  push:
    branches:
      - main  # This workflow triggers on pushes to the main branch

jobs:
  update-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          cd server
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update requirements.txt
        run: |
          cd server
          pip freeze > requirements.txt

      - name: Commit changes
        run: |
          cd server
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add requirements.txt
          git commit -m "Update requirements.txt" || echo "No changes to commit"
          git push origin main  # Push changes back to the main branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token to push changes
